inherit_from: .rubocop_todo.yml

# Offense count: 4
Metrics/AbcSize:
  Max: 40

# Offense count: 1
# Configuration parameters: CountComments.
#Metrics/ClassLength:
#  Max: 200

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Offense count: 23
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# Offense count: 3
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 200

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: auto_detection, squiggly, active_support, powerpack, unindent
Layout/IndentHeredoc:
  Exclude:
    - 'spec/thor/completion_spec.rb'

# Offense count: 3
Security/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 3
Style/EvalWithLocation:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 40
